### ISSUE TITLE
README update required

### ISSUE THREAD

**Issue by zameel7** [zameel7/bulk-certificate#2]

**Comment by ankit060801** [comment]
Can you please elaborate the details of updates??

**Comment by JoydeepMallick** [comment]
Could you please explain the required documentation and assign this to me ?

**Comment by Subhajit767** [comment]
I want to work on this so please assign this to me

**Comment by zameel7** [comment]
@JoydeepMallick , @Subhajit767 , @ankit060801 
README could be modified if you think there is something to be modified. You could make suggestions.
If I found your suggestion to be worth it, I'll assign that to you!
You could try the app by cloning and running it in jupyter notebook or through google colab

**Comment by JoydeepMallick** [comment]
I could try to elaborate each step of the code as per my conveineince.

**Comment by zameel7** [comment]
> I could try to elaborate each step of the code as per my conveineince.

@JoydeepMallick , please do it and send a PR
